### ISSUE TITLE
Programs with no update() function and event listeners end after start() in app but not java.

### ISSUE THREAD

**Issue by bcauchon** [davecparker/code12#244]
```
class MyProgram
{
	// Declare your class-level variables here

	public void start()
	{
		// Your code here runs once at the start of running the program
		ct.circle( ct.getWidth() / 2, ct.getHeight() / 2, 50 );
	}
	
	public void onMousePress( GameObj obj, double x, double y )
	{
		ct.println( "onMousePress" );
	}
}
```

**Comment by davecparker** [comment]
I fixed this by removing the special "ended" runtime state. I realized that in addition to these cases, there might be GameObjs with xSpeed or ySpeed set, and we want to see them continue to animate. Rather than try to detect all such cases, I now just keep all programs running until stopped or restarted by the user.

**Comment by bcauchon** [comment]
Fix verified on master.
