### ISSUE TITLE
Variables labeled 'end' are 'nil' in watch window

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#304]
Any instance variables named 'end' appear as 'nil' in the watch window. In my 'Game.java' use case test, I have an instance variable of type boolean labeled 'end' that exclusively remains as 'nil' during the program's execution in the Code12 runtime. This seems to occur because of lua's built-in keyword 'end'.

**Comment by davecparker** [comment]
This is because "end" is a reserved word in Lua, and variables named the same as Lua reserved words get prefixed with an underscore, so varWatch needs to look it up as "_end".

To fix this, varWatch needs to do the equivalent of 
```
varName = nameFromLuaReservedWord[varName] or varName
```
as done in codeGenJava.lua, although this is currently file local to codeGenJava.

**Comment by davecparker** [comment]
Fixed by having codeGenJava export a function codeGenJava.luaName( name ) to get the Lua variable name for a Java name, and used this in varWatch.
