### ISSUE TITLE
Windows key cases exception

### ISSUE THREAD

**Issue by bcauchon** [davecparker/code12#8]
"Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 524"

**Comment by davecparker** [comment]
Can you fix since, since you're running Windows and can test/verify?
In GameInput.java, I use KeyEvent.KEY_LAST to size the keyCodeToName array, but perhaps this is not good enough and the Windows key is actually outside this range? You could hard-code a larger value or perhaps use ArrayList instead.

**Comment by bcauchon** [comment]
Fix done on my runtime branch, not yet merged into master.

**Comment by bcauchon** [comment]
Fix verified.

**Comment by davecparker** [comment]
Looking into another keyboard bug I found (ct.keyPressed crashes if the user gives an invalid key name -- oops), I don't see any signs of the above fix in GameInput.java. What was the fix? Did it get merged in?

**Comment by bcauchon** [comment]
I think I forgot to copy my fix in GameInput.java before I deleted my old runtime branch. Then I must have closed the issue after the line hits were merged in without retesting this issue after updated from master.
I will submit a pull request with the fix. Sorry for the error.

**Comment by bcauchon** [comment]
Fixed in #160
